version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: pmevent-db
    restart: no
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pm-event
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  postgres-test:
    image: postgres:latest
    container_name: pmevent-db-test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: pm-event-test
    ports:
      - "5433:5432"

volumes:
  postgres_data: