version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pmevent-db
    restart: no
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pm-event
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: