spring:
  application:
    name: pmevent
  datasource:
    url: jdbc:postgresql://localhost:5432/pm-event
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    fr.pmevent: DEBUG